### ISSUE TITLE
No module named "billards_env" for gym environment

### ISSUE THREAD

**Issue by 2000222** [jlko/STOVE#1]
Hi, I run the model/main_rl.py and I want to try the gym environment such as
 python main_rl.py --gym 'True' 
but I obtain the mistake like this:
      from runners import PPORunner
      from billards_env import BillardsEnv, AvoidanceTask
      ModuleNotFoundError: No module named 'billards_env'
Could you share the billards_env.py?
Thanks a lot~

**Comment by jlko** [comment]
Hey Sarah,

thanks for reaching out! Sorry you are experiencing problems with our code.

If you are interested in *STOVE*, you do not need to run anything from the `/model/rl/` folder, which implements the PPO baseline for the model-based control experiments. We hope that all code directly related to STOVE works well!

If you are interested in playing with the billiards environment only, you can find it at `model/envs/envs.py`. 

If you are indeed interested in the PPO implementation, this section of the code may have some problems with imports due to a previous code restructure.
@marcelhussing is responsible for that section of the code and I have reached out to him. Hopefully he can give his code a good check-up.

However, as an initial band-aid, I have implemented some obvious fixes and the PPO baseline should now be available as `python run_scripts.py --ppo_baseline`.
See the git diff for commit 8cbb7da856c18c6eb75d86030dbbf42b067ab559 I just pushed.

Hope that fixes things. If not, I hope that Marcel soon finds some time to help you with this.

Best,
Jannik

**Comment by jlko** [comment]
Fixed with commit 61d949320fc0bf1a8dba09b3845bddcd153b1a64

**Comment by jlko** [comment]
Fixed with commit 61d949320fc0bf1a8dba09b3845bddcd153b1a64

**Comment by jlko** [comment]
Fixed with commit 61d949320fc0bf1a8dba09b3845bddcd153b1a64.

**Comment by jlko** [comment]
Fixed with commit 8cbb7da856c18c6eb75d86030dbbf42b067ab559.
